version: '3.8'

# Configuraciones comunes para todos los servicios de Airflow
x-airflow-common:
  &airflow-common
  build: .
  environment:
    # Cargamos las credenciales del user de AWS para que Airflow pueda usar los recursos de AWS (S3,etc)
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_REGION=${AWS_REGION}
    - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    # Conectamos Airflow a tu misma base de datos para que guarde su configuración ahí
    - NEWS_API_KEY=${NEWS_API_KEY}
    - DB_HOST=${DB_HOST}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db_postgres:5432/${DB_NAME}
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=false # Apagamos los ejemplos por defecto
    - RAW_DATA_PATH=${RAW_DATA_PATH}
    - PROCESSED_DATA_PATH=${PROCESSED_DATA_PATH}
    - SLACK_WEBHOOK=${SLACK_WEBHOOK}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src
    - ./data:/opt/airflow/data
  depends_on:
    - db_postgres

services:
  # 1. Tu Base de Datos de Noticias (Intacta)
  db_postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. El Inicializador (Solo corre una vez para crear las tablas internas de Airflow)
  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: version
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db_postgres:5432/${DB_NAME}
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin # <--- Con esto entrarás a la web de Airflow

  # 3. El Webserver (La interfaz gráfica que veremos en el navegador)
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    restart: always
    command: webserver
    ports:
      - "8080:8080" # Airflow vivirá en tu puerto 8080
    depends_on:
      - airflow-init

  # 4. El Scheduler (El Programador que vigilará el reloj)
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    restart: always
    command: scheduler
    depends_on:
      - airflow-init

volumes:
  postgres_data: